version: '3.8'
name: next_server
services:
  database:
    image: mysql:8.3.0
    container_name: ${COMPOSE_PROJECT_NAME}_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${MYSQL_TZ-Asia/Shanghai}
    ports:
      - ${EXPOSE_DB_PORT-3306}:3306
    volumes:
      - ${VOLUME_DB}:/var/lib/mysql
  
  backend:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    image: ${COMPOSE_PROJECT_NAME}_backend_image
    container_name: ${COMPOSE_PROJECT_NAME}_backend
    restart: always
    ports:
      - ${EXPOSE_BACKEND_PORT}:3000

  frontend:
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
    image: ${COMPOSE_PROJECT_NAME}_frontend_image
    container_name: ${COMPOSE_PROJECT_NAME}_frontend
    restart: always
    ports:
      - ${EXPOSE_FRONTEND_PORT}:80

  server:
    build: 
      context: ./server/
      dockerfile: Dockerfile
    image: ${COMPOSE_PROJECT_NAME}_omp_image
    container_name: ${COMPOSE_PROJECT_NAME}_omp
    restart: always
    ports:
      - ${EXPOSE_SERVER_PORT}:7777
    volumes:
      - ${VOLUME_SERVER}:/app
